FROM maven:3.9.6-eclipse-temurin-17-alpine

WORKDIR /app

# Copy pom.xml to cache dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source files
COPY src ./src

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]