spring.application.name=demo
spring.data.mongodb.database=mangadex_cloud_db
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/mangacloud_db}
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.serialization.write-dates-as-timestamps=false

# Redis / Cache Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=${CACHE_TYPE:simple}
spring.cache.redis.time-to-live=600000

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# Ép Console Log hiển thị UTF-8
vaadin.console.utf8=true
logging.charset.console=UTF-8

# MangaDex API & Uploads CDN External Configs
mangadex.api.base-url=https://api.mangadex.org/
mangadex.uploads.url=https://uploads.mangadex.org/
